# Generated by Django 6.1 on 2026-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="URL-friendly identifier, e.g 'knotless-braids medium-length'", unique=True)),
                ('category', models.CharField(choices=[('Knotless_Braids', 'knotless braids'), ('Boho_Locs', 'boho locs'), ('Cornrows', 'cornrows'), ('Box_Braids', 'box braids'), ('Other', 'other')], default='Other', max_length=30)),
                ('description', models.TextField()),
                ('prep_required', models.TextField(help_text='What the client should do before their appointment')),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Appointment duration in minutes')),
                ('maintenance_guidelines', models.TextField(help_text='How the client should maintain their style')),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this style from the website without deleting it')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
