# Generated by Django 6.1 on 2026-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='The main image for this style, displayed on the website', null=True, upload_to='styles/'),
        ),
    ]
