# Generated by Django 6.1 on 2026-08-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_style_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='styles/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Check this box to feature this image on the homepage')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(blank=True, help_text='Optional: Link this photo to a specific style', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='core.style')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
