# Generated by Django 6.1 on 2026-08-18 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('requested_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True, help_text='Optional: Any additional information or requests from the client')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Check this box to confirm the booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='core.style')),
            ],
            options={
                'ordering': ['-requested_datetime'],
            },
        ),
    ]
