# Generated by Django 6.1 on 2026-08-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_confirmed',
        ),
    ]
